FROM ros:foxy

# 필수 패키지 설치
RUN apt update 
RUN apt-get install -y python3.8 python3-pip 
RUN apt-get install -y ros-foxy-rmw-cyclonedds-cpp
RUN apt-get install -y libgl1-mesa-glx
RUN apt-get install -y python3-opencv
RUN apt-get install -y ros-foxy-cv-bridge

COPY img_view/img_path_pub.py /img_path_pub.py

# ROS 2 환경 자동 적용
SHELL ["/bin/bash", "-c"]
RUN echo "source /opt/ros/foxy/setup.bash" >> ~/.bashrc

ENV RMW_IMPLEMENTATION=rmw_cyclonedds_cpp

ENV ROS_DOMAIN_ID=10

# Setup entrypoint for ROS2 environment
COPY ./ros2_entrypoint_underlay.sh /
ENTRYPOINT ["/ros2_entrypoint_underlay.sh"]


# img_path_pub을 실행
CMD ["python3", "img_path_sub.py"]

