FROM ros:foxy

# 필수 패키지 설치
RUN apt-get update && apt-get install -y \
    ros-foxy-usb-cam \
 && rm -rf /var/lib/apt/lists/*

# ROS 2 환경 자동 적용
SHELL ["/bin/bash", "-c"]
RUN echo "source /opt/ros/foxy/setup.bash" >> ~/.bashrc

#ENV ROS_DOMAIN_ID=10

# Setup entrypoint for ROS2 environment
COPY ./ros2_entrypoint_underlay.sh /
ENTRYPOINT ["/ros2_entrypoint_underlay.sh"]


# 기본 shell로 bash 제공
CMD ["ros2", "run",  "usb_cam", "usb_cam_node_exe"]

